version: '3.9'

services:
  reverseproxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./utils/docker-nginx/certs:/certs
    ports:
      - 80:80
      - 443:443

  binaryrepo:
    image: binaryrepo_binaryrepo
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    ports:
      - "2345:2345"
      - "8081:8081"
    expose:
      - "2345"
    volumes:
      - .:/src
