version: '3.9'

services:

  binaryrepo:
    container_name: binaryrepo
    image: binaryrepo:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - filestore-data:/tmp/filestore
    depends_on:
      - postgres

  reverseproxy:
    container_name: binaryrepo-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certs:/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - binaryrepo

  postgres:
    container_name: binaryrepo-postgres
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - default

volumes:
  filestore-data: