version: '3.9'

services:

  binaryrepo:
    user: "${UID}:${GID}"
    container_name: binaryrepo
    build: ./docker
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace

  reverseproxy:
    container_name: binaryrepo-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/certs:/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - binaryrepo

  postgres:
    container_name: binaryrepo-postgres
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - default
