version: '3.1'

services:
  reverseproxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
    ports:
      - 80:80
      - 443:443

  binaryrepo:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /src/build/binaryrepo run
    working_dir: /src
    ports:
      - "2345:2345"
      - "8081:8081"
    expose:
      - "2345"
    volumes:
      - .:/src
